ENV_1A_EASY = "resources/envs/1a_easy.json"
ENV_1A_3_BLOCKS = "resources/envs/1a_3_blocks.json"
ENV_1A_MEDIUM = "resources/envs/1a_medium.json"
ENV_4A_EASY = "resources/envs/4a_easy.json"
ENV_4A_MEDIUM = "resources/envs/4a_medium.json"
